using System;

#nullable disable

namespace NeurocorBackEnd.Domain.Entities
{
    public partial class Paciente
    {
        public int CdPaciente { get; set; }
        public long? CdCidade { get; set; }
        public byte? CdDisSan { get; set; }
        public string TpSituacao { get; set; }
        public string NmMnemonico { get; set; }
        public string NmPaciente { get; set; }
        public string TpSexo { get; set; }
        public string TpEstadoCivil { get; set; }
        public long? CdCidadeTem { get; set; }
        public string DsEndereco { get; set; }
        public DateTime DtCadastro { get; set; }
        public DateTime? DtNascimento { get; set; }
        public string TpCor { get; set; }
        public string NmMae { get; set; }
        public byte? CdClaEco { get; set; }
        public byte? CdCidadania { get; set; }
        public byte? CdTipMor { get; set; }
        public byte? CdTipRes { get; set; }
        public byte? CdGrauIns { get; set; }
        public byte? CdReligiao { get; set; }
        public byte? CdProfissao { get; set; }
        public string NrCep { get; set; }
        public string NrDocumento { get; set; }
        public DateTime? HrCadastro { get; set; }
        public string NrFone { get; set; }
        public string NmBairro { get; set; }
        public string NmPai { get; set; }
        public byte? CdDisSanMuitos { get; set; }
        public string DsTrabalho { get; set; }
        public string NmConjuge { get; set; }
        public string TpSanguineo { get; set; }
        public string SnDoador { get; set; }
        public string DsChecapac { get; set; }
        public string NmUsuario { get; set; }
        public string CdCns { get; set; }
        public string NrCns { get; set; }
        public string NrCpf { get; set; }
        public string DsComplemento { get; set; }
        public int? NrEndereco { get; set; }
        public decimal? NrRgNasc { get; set; }
        public string NrIdentidade { get; set; }
        public string DsOmIdentidade { get; set; }
        public string DsObservacao { get; set; }
        public string CdPacienteAntigo { get; set; }
        public DateTime? DtUltimaAtualizacao { get; set; }
        public long? CdNaturalidade { get; set; }
        public byte CdMultiEmpresa { get; set; }
        public string DsAtributo1 { get; set; }
        public string SnAltDadosOraApp { get; set; }
        public string Email { get; set; }
        public string CdPacienteIntegra { get; set; }
        public DateTime? DtIntegra { get; set; }
        public decimal? CdSeqIntegra { get; set; }
        public DateTime? DtInativo { get; set; }
        public string CdPisPasep { get; set; }
        public string TpCertidao { get; set; }
        public string NmCartorio { get; set; }
        public string DsLivro { get; set; }
        public string DsFolha { get; set; }
        public DateTime? DtEmissaoCertidao { get; set; }
        public DateTime? DtEmissaoIdentidade { get; set; }
        public string CdUfEmissaoIdentidade { get; set; }
        public DateTime? DtEntradaEstrangeiro { get; set; }
        public string NrCtps { get; set; }
        public string NrSerieCtps { get; set; }
        public DateTime? DtEmissaoCtps { get; set; }
        public string CdUfEmissaoCtps { get; set; }
        public string NrTituloEleitoral { get; set; }
        public string NrZonaTituloEleitoral { get; set; }
        public string NrSecaoTituloEleitoral { get; set; }
        public string SnRecebeContato { get; set; }
        public long? CdTipoLogradouro { get; set; }
        public string SnPermiteAgendarParaSus { get; set; }
        public byte? CdCategoriaOpiniao { get; set; }
        public string SnVip { get; set; }
        public byte? CdPais { get; set; }
        public string CdPacienteExterno { get; set; }
        public byte? CdEtnia { get; set; }
        public string DsHash { get; set; }
        public byte? NrDddFone { get; set; }
        public byte? NrDddCelular { get; set; }
        public string NrCelular { get; set; }
        public string SnNotificacaoSms { get; set; }
        public string NmPacienteFonetizado { get; set; }
        public int? CdSituacaoFamiliar { get; set; }
        public DateTime DtCadastroManual { get; set; }
        public string NrDocumentoEstrangeiro { get; set; }
        public DateTime? DtEntradaBrasil { get; set; }
        public DateTime? DtNaturalizacao { get; set; }
        public string NrPortariaNaturalizacao { get; set; }
        public string DsPrimeiroNome { get; set; }
        public string DsPrimeiroSobrenome { get; set; }
        public string DsSegundoSobrenome { get; set; }
        public string CdIdentificadorPessoa { get; set; }
        public string CdEnderecoPostal { get; set; }
        public decimal? NrDdiFone { get; set; }
        public decimal? NrDdiCelular { get; set; }
        public decimal? NrDdiFoneComercial { get; set; }
        public decimal? NrDddFoneComercial { get; set; }
        public decimal? NrFoneComercial { get; set; }
        public string SnAtivo { get; set; }
        public string DsCoagulopatia { get; set; }
        public string NrSame { get; set; }
        public string SnUtilizaNomeSocial { get; set; }
        public string NmSocialPaciente { get; set; }
        public string SnEnderecoSemNumero { get; set; }
        public string SnEnderecoExterno { get; set; }
        public byte? CdBanco { get; set; }
        public string NrAgencia { get; set; }
        public string DsAgencia { get; set; }
        public string NrConta { get; set; }
        public string SnFrequentaEscola { get; set; }
        public string DsCargoTrabalho { get; set; }
        public string NrRegistroFuncionalTrabalho { get; set; }
        public string DsVincluloTrabalho { get; set; }
        public string DsHorarioTrabalho { get; set; }
        public string TpPaciente { get; set; }
        public byte? CdTipParen { get; set; }
        public string DsComplementoTutor { get; set; }
        public string NmTutor { get; set; }
        public DateTime? DtNascimentoTutor { get; set; }
        public string TpSexoTutor { get; set; }
        public string NrCpfTutor { get; set; }
        public string NrDeclaracaoNascidoVivo { get; set; }
        public string CdTipoBeneficiario { get; set; }
        public string CdIdentificadorConvenio { get; set; }
        public string CdIdentificadorConvenioPai { get; set; }
        public byte? CdTipParenConvenio { get; set; }
        public string SnPlanoOdontologico { get; set; }
        public string CdUsuarioPermissao { get; set; }
        public decimal? CdMotAusenciaDocObrg { get; set; }
        public decimal? CdLocalTrabalhoChile { get; set; }
        public long? CdCondicaoEspecial { get; set; }
        public int? CdCorAreaFamilia { get; set; }
        public string SnRutFicticio { get; set; }
        public DateTime? DtValidade { get; set; }
        public decimal? CdForcaMilitar { get; set; }
        public decimal? CdPostoMilitar { get; set; }
        public decimal? CdLogLogradouro { get; set; }
        public string NmUsuarioUltimaAtualizacao { get; set; }
        public string NrNif { get; set; }
    }
}
